modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All Rights Reserved"

issueTrackerURL="https://github.com/allkillernofill3r/WoodOres/issues" #optional

[[mods]] #mandatory

modId="woodores" #mandatory

version="1.0.0" #mandatory

displayName="Wood Ores" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/wood-ores" #optional

logoFile="woodores_logo.png" #optional

authors="allkillernofiller (Killer_Playz)" #optional

description='''
Adds ores that give you wood!
'''

[[dependencies.woodores]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.woodores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
